<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="4" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[==================On Start ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
    </line>
    <line>
      <![CDATA[==================On Start End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Start ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[Executing Method is: --------------test_postUser---------------]]>
    </line>
    <line>
      <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@2b736fee]]>
    </line>
    <line>
      <![CDATA[==================Test End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@2b736fee]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Start ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[Executing Method is: --------------test_getUserByName---------------]]>
    </line>
    <line>
      <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@38caad07]]>
    </line>
    <line>
      <![CDATA[==================Test End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@38caad07]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Start ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[Executing Method is: --------------test_updateUserByname---------------]]>
    </line>
    <line>
      <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@512dc0e0]]>
    </line>
    <line>
      <![CDATA[==================Test End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@512dc0e0]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Start ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[Executing Method is: --------------test_deleteUser---------------]]>
    </line>
    <line>
      <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@79fcd194]]>
    </line>
    <line>
      <![CDATA[==================Test End ========================]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure ========================]]>
    </line>
    <line>
      <![CDATA[Thread Id: 1]]>
    </line>
    <line>
      <![CDATA[Thread Name: main]]>
    </line>
    <line>
      <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@79fcd194]]>
    </line>
    <line>
      <![CDATA[==================On Test Failure End ========================]]>
    </line>
  </reporter-output>
  <suite started-at="2023-10-21T11:54:11 IST" name="Suite" finished-at="2023-10-21T11:54:22 IST" duration-ms="10824">
    <groups>
    </groups>
    <test started-at="2023-10-21T11:54:11 IST" name="Test" finished-at="2023-10-21T11:54:22 IST" duration-ms="10824">
      <class name="api.test.UserTests2">
        <test-method is-config="true" signature="setupData()[pri:0, instance:api.test.UserTests2@478190fc]" started-at="2023-10-21T11:54:11 IST" name="setupData" finished-at="2023-10-21T11:54:12 IST" duration-ms="1215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupData -->
        <test-method signature="test_postUser()[pri:1, instance:api.test.UserTests2@478190fc]" started-at="2023-10-21T11:54:12 IST" name="test_postUser" finished-at="2023-10-21T11:54:17 IST" duration-ms="4304" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.test.UserTests2.test_postUser(UserTests2.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[==================On Test Start ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[Executing Method is: --------------test_postUser---------------]]>
            </line>
            <line>
              <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@2b736fee]]>
            </line>
            <line>
              <![CDATA[==================Test End ========================]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@2b736fee]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure End ========================]]>
            </line>
          </reporter-output>
        </test-method> <!-- test_postUser -->
        <test-method signature="test_getUserByName()[pri:2, instance:api.test.UserTests2@478190fc]" started-at="2023-10-21T11:54:17 IST" name="test_getUserByName" finished-at="2023-10-21T11:54:18 IST" duration-ms="1211" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.test.UserTests2.test_getUserByName(UserTests2.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[==================On Test Start ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[Executing Method is: --------------test_getUserByName---------------]]>
            </line>
            <line>
              <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@38caad07]]>
            </line>
            <line>
              <![CDATA[==================Test End ========================]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@38caad07]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure End ========================]]>
            </line>
          </reporter-output>
        </test-method> <!-- test_getUserByName -->
        <test-method signature="test_updateUserByname()[pri:3, instance:api.test.UserTests2@478190fc]" started-at="2023-10-21T11:54:18 IST" name="test_updateUserByname" finished-at="2023-10-21T11:54:20 IST" duration-ms="2587" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.test.UserTests2.test_updateUserByname(UserTests2.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[==================On Test Start ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[Executing Method is: --------------test_updateUserByname---------------]]>
            </line>
            <line>
              <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@512dc0e0]]>
            </line>
            <line>
              <![CDATA[==================Test End ========================]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@512dc0e0]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure End ========================]]>
            </line>
          </reporter-output>
        </test-method> <!-- test_updateUserByname -->
        <test-method signature="test_deleteUser()[pri:4, instance:api.test.UserTests2@478190fc]" started-at="2023-10-21T11:54:20 IST" name="test_deleteUser" finished-at="2023-10-21T11:54:22 IST" duration-ms="1099" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.test.UserTests2.test_deleteUser(UserTests2.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[==================On Test Start ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[Executing Method is: --------------test_deleteUser---------------]]>
            </line>
            <line>
              <![CDATA[This is created Reporter: com.aventstack.extentreports.ExtentReports@2805d709]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@79fcd194]]>
            </line>
            <line>
              <![CDATA[==================Test End ========================]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure ========================]]>
            </line>
            <line>
              <![CDATA[Thread Id: 1]]>
            </line>
            <line>
              <![CDATA[Thread Name: main]]>
            </line>
            <line>
              <![CDATA[This is created Test: com.aventstack.extentreports.ExtentTest@79fcd194]]>
            </line>
            <line>
              <![CDATA[==================On Test Failure End ========================]]>
            </line>
          </reporter-output>
        </test-method> <!-- test_deleteUser -->
      </class> <!-- api.test.UserTests2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
